# Change these first
owner: Monkee-Boy # Your GitHub organization or username, where this repository lives
repo: site-monitor # The name of this repository

sites:
  - name: Monkee-Boy
    url: https://www.monkee-boy.com/
  - name: The Story of Texas
    url: https://www.thestoryoftexas.com/
  - name: ABC Home and Commercial
    url: https://www.abchomeandcommercial.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /site-monitor
  logoUrl: https://avatars.githubusercontent.com/u/6999936
  name: Site Monitor
  introTitle: "**Monkee-Boy** Site Monitoring"
  introMessage: Monitoring uptime for a variety of Monkee-Boy sites, projects, and servers.
  navbar:
    - title: Status
      href: /
    - title: monkee-boy.com
      href: https://www.monkee-boy.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
